services:
  couchdb:
    image: couchdb:3
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
volumes:
  couchdb_data:
